// resources/tentative/newssite/news-nuxt/components/atoms/Modal.vue
<script lang="js">
import styles from "news-site-css/dist/modal.module.css";

import { login } from "~/data/form";

export default {
    props: {
        onClose: Function,
    },
    data() {
        return {
            styles,
            login
        }
    },
    methods: {
        handleSubmit(e) {
            const { elements } = e.target;
            console.log(elements.username.value, elements.password.value);
            this.onClose();
        },
    }
}
</script>

<template>
  <div
    id="login"
    :class="[styles.modal, styles.open]"
  >
    <div :class="styles['modal-content']">
      <button
        id="modal-dialog-link"
        :class="styles['modal-close-button']"
        title="Close Button"
        @click="onClose"
      >
        <div
          :class="[styles['modal-close-button-icon'], 'animated-icon', 'close-icon', 'hover']"
          title="Close Icon"
        >
          <span class="animated-icon-inner">
            <span />
            <span />
          </span>
        </div>
      </button>
      <header :class="styles['modal-header']">
        <h2>{{ login.header }}</h2>
      </header>
      <section :class="styles['modal-body']">
        <Form
          :on-cancel="onClose"
          :on-submit="handleSubmit"
        />
      </section>
    </div>
  </div>
</template>

// resources/tentative/newssite/news-rtl/src/components/modal/modal.jsx
import classNames from "classnames";

import Form from "../form/form";
import { login } from "@/data/form";

import styles from "news-site-css/dist/modal.module.css";

export default function Modal({ onClose }) {
    function handleSubmit(e) {
        const { elements } = e.target;
        console.log(elements.username.value, elements.password.value);
        onClose();
    }

    return (
        <div id="login" className={classNames(styles.modal, styles.open)}>
            <div className={styles["modal-content"]}>
                <button id="close-modal-link" className={styles["modal-close-button"]} onClick={onClose} title="Close Button">
                    <div className={classNames(styles["modal-close-button-icon"], "animated-icon", "close-icon", "hover")} title="Close Icon">
                        <span className="animated-icon-inner">
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                </button>
                <header className={styles["modal-header"]}>
                    <h2>{login.header}</h2>
                </header>
                <section className={styles["modal-body"]}>
                    <Form onCancel={onClose} onSubmit={handleSubmit} />
                </section>
            </div>
        </div>
    );
}
