// resources/newssite/news-next/src/partials/section/section.jsx
import Article from "@/components/article/article";

import styles from "news-site-css/dist/layout.module.css";

export default function Section({ section }) {
    return (
        <>
            {section.name
                ? <div id={section.id} className={styles["row-header"]}>
                    <h2>{section.name}</h2>
                </div>
                : null}
            <section className={styles.row}>
                {section.articles.map((article, index) =>
                    <Article key={article.id} article={article} />
                )}
            </section>
        </>
    );
}

// resources/newssite/news-nuxt/components/molecules/Section.vue
<script lang="js">
import styles from "news-site-css/dist/layout.module.css";
export default {
    props: {
        section: Object,
    },
    data() {
        return {
            styles,
        };
    },
};
</script>

<template>
    <div v-if="section?.name" :id="section.id" :class="styles['row-header']">
        <h2>{{ section.name }}</h2>
    </div>
    <section :class="styles.row">
        <Article v-for="(articles, index) in section.articles" :key="`${section.id}-${index}`" :article="articles" />
    </section>
</template>
