// resources/tentative/newssite/news-next/src/components/input/input.jsx
import classNames from "classnames";

import styles from "news-site-css/dist/input.module.css";

export default function Input({ id = "input", placeholder = "Enter Something", label = "Enter Something", containerClass, type, onChange }) {
    function handleChange(e) {
        onChange?.(e);
    }

    return (
        <div className={classNames(
            styles["input-container"],
            containerClass
        )}>
            <label className={classNames( styles.label, "visually-hidden")} htmlFor={id}>{label}</label>
            <input className={classNames( styles.input, styles["input-type-text"])} type={type} autoComplete="off" id={id} placeholder={placeholder} onChange={handleChange}/>
        </div>
    );
}

// resources/tentative/newssite/news-nuxt/components/atoms/Input.vue
<script lang="js">
import styles from "news-site-css/dist/input.module.css";

export default {
    props: {
        id: String,
        placeholder: String,
        label: String,
        containerClass: String,
        type: String,
        onChange: Function
    },
    data() {
        return {
            styles,
        }
    },
    methods: {
        handleChange(e) {
           this.onChange(e);
        }
    }
}
</script>

<template>
  <div :class="[styles['input-container'], containerClass]">
    <label
      :class="[styles.label, 'visually-hidden']"
      :v-for="id"
    >{{ label }}</label>
    <input
      :id="id"
      :class="[styles.input, styles['input-type-text']]"
      :type="type"
      autocomplete="off"
      :placeholder="placeholder"
      :onInput="handleChange"
    >
  </div>
</template>
