// resources/newssite/news-next/src/components/toast/toast.jsx
import classNames from "classnames";
import toastStyles from "news-site-css/dist/toast.module.css";
import buttonStyles from "news-site-css/dist/button.module.css";

export default function Toast({ onClose, notification, onAccept, onReject }) {
    const { title, description, actions } = notification;
    return (
        <div className={classNames(toastStyles.toast, toastStyles.open)}>
            <button
                id="close-toast-link"
                className={toastStyles["toast-close-button"]}
                onClick={onClose}
                title="Close Button"
            >
                <div
                    className={classNames(
                        toastStyles["toast-close-button-icon"],
                        "animated-icon",
                        "close-icon",
                        "hover",
                    )}
                    title="Close Icon"
                >
                    <span className="animated-icon-inner">
                        <span></span>
                        <span></span>
                    </span>
                </div>
            </button>
            {title
                ? <header className={toastStyles["toast-header"]}>
                    <h2>{title}</h2>
                </header>
                : null}
            <section className={toastStyles["toast-body"]}>
                <div className={toastStyles["toast-description"]}>{description}</div>
                <div className={toastStyles["toast-actions"]}>
                    {actions.map((action) => {
                        const id = `toast-${action.type}-button`;
                        return (
                            <button
                                key={id}
                                id={id}
                                className={classNames(
                                    buttonStyles.button,
                                    buttonStyles[`${action.priority}-button`],
                                    toastStyles["toast-actions-button"],
                                )}
                                onClick={action.type === "accept" ? onAccept : onReject}
                            >
                                {action.name}
                            </button>
                        );
                    })}
                </div>
            </section>
        </div>
    );
}

// resources/tentative/newssite/news-nuxt/components/atoms/Toast.vue
<script lang="js">
import toastStyles from "news-site-css/dist/toast.module.css";
import buttonStyles from "news-site-css/dist/button.module.css";

export default {
    props: {
        onClose: Function,
        onAccept: Function,
        onReject: Function,
        notification: Object
    },
    data() {
        return {
            toastStyles,
            buttonStyles,
            callbacks: {
                'accept': this.onAccept,
                'reject': this.onReject,
            }
        }
    },
}
</script>

<template>
  <div :class="[toastStyles.toast, toastStyles.open]">
    <button
      id="close-toast-link"
      :class="toastStyles['toast-close-button']"
      @click="onClose"
    >
      <div
        :class="[toastStyles['toast-close-button-icon'], 'animated-icon', 'close-icon', 'hover']"
        title="Close Icon"
      >
        <span class="animated-icon-inner">
          <span />
          <span />
        </span>
      </div>
    </button>
    <header
      v-if="notification.title"
      :class="toastStyles['toast-header']"
    >
      <h2>{{ notification.title }}</h2>
    </header>
    <section :class="toastStyles['toast-body']">
      <div :class="toastStyles['toast-description']">
        {{ notification.description }}
      </div>
      <div :class="toastStyles['toast-actions']">
        <button
          v-for="action in notification.actions"
          :id="`toast-${action.type}-button`"
          :key="`toast-${action.type}-button`"
          :class="[buttonStyles.button, buttonStyles[`${action.priority}-button`], toastStyles['toast-actions-button']]"
          @click="callbacks[action.type]"
        >
          {{ action.name }}
        </button>
      </div>
    </section>
  </div>
</template>
