// resources/newssite/news-nuxt/components/atoms/Dropdown.vue
<script lang="js">
import { more } from "~/data/buttons";
import styles from "news-site-css/dist/dropdown.module.css";
export default {
    props: {
        animatedIconClass: String,
    },
    data() {
        return {
            more,
            styles,
            isOpen: false,
        }
    },
    methods: {
        closeDropdown() {
            this.isOpen = false;
        },
        handleChange(e) {
            this.isOpen = e.target.checked;
        }
    }
}
</script>

<template>
    <div :class="styles.dropdown">
        <input id="navbar-dropdown-toggle" type="checkbox" :class="styles['dropdown-toggle']" :checked="isOpen" @change="handleChange" />
        <label for="navbar-dropdown-toggle" :class="styles['dropdown-label']">
            <span :class="styles['dropdown-label-text']">{{ more.label }}</span>
            <div :class="['animated-icon', 'arrow-icon', 'arrow', animatedIconClass]">
                <span class="animated-icon-inner" title="Arrow Icon">
                    <span />
                    <span />
                </span>
            </div>
        </label>
        <ul :class="styles['dropdown-content']" @click="closeDropdown">
            <slot />
        </ul>
    </div>
</template>

// resources/newssite/news-next/src/components/dropdown/dropdown.jsx
import { useState } from "react";
import classNames from "classnames";

import { useDataContext } from "@/context/data-context";

import styles from "news-site-css/dist/dropdown.module.css";

export default function Dropdown({ children, animatedIconClass }) {
    const [isOpen, setIsOpen] = useState(false);
    const { buttons } = useDataContext();

    function handleChange(e) {
        setIsOpen(e.target.checked);
    }

    function closeDropdown() {
        setIsOpen(false);
    }

    return (
        <div className={styles.dropdown}>
            <input
                type="checkbox"
                id="navbar-dropdown-toggle"
                className={styles["dropdown-toggle"]}
                onChange={handleChange}
                checked={isOpen}
            />
            <label htmlFor="navbar-dropdown-toggle" className={styles["dropdown-label"]}>
                <span className={styles["dropdown-label-text"]}>{buttons.more.label}</span>
                <div className={classNames("animated-icon", "arrow-icon", "arrow", animatedIconClass)}>
                    <span className="animated-icon-inner" title="Arrow Icon">
                        <span></span>
                        <span></span>
                    </span>
                </div>
            </label>
            <ul className={styles["dropdown-content"]} onClick={closeDropdown}>
                {children}
            </ul>
        </div>
    );
}
