// resources/tentative/newssite/news-nuxt/components/atoms/ArticleHeader.vue
<script lang="js">
    export default {
        props: {
            headerClass: String,
            text: String,
            link: String,
        }
    }
</script>

<template>
    <header v-if="text" :class="headerClass">
        <a v-if="link" href="link"><h2>{{ text }}</h2></a>
        <h2 v-else>{{ text }}</h2>
    </header>
</template>

// resources/tentative/newssite/news-next/src/components/article/article-header.jsx
export default function ArticleHeader({ text, headerClass, link }) {
    if (!text)
        return null;

    return (
        <header className={headerClass}>
            {link ? <a href={link}>
                <h2>{text}</h2>
            </a>
                : <h2>{text}</h2>
            }
        </header>
    );
}
