// resources/newssite/news-nuxt/components/atoms/ArticleTag.vue
<script lang="js">
import styles from "news-site-css/dist/article.module.css";

export default {
    props: {
        tag: Object,
    },
    data() {
        return {
            styles,
        };
    },
};
</script>

<template>
    <div v-if="tag" :class="[styles['article-image-tag'], styles[tag.type]]">
        <LightningIcon v-if="tag.type === 'breaking'" />
        <PlayIcon v-if="tag.type === 'watch'" />
        <FireIcon v-if="tag.type === 'new'" />
        <ArticleText :text="tag.label" />
    </div>
</template>

// resources/tentative/newssite/news-next/src/components/article/article-tag.jsx
import classNames from "classnames";

import ArticleText from "./article-text";
import LightningIcon from "@/assets/lightning-icon";
import PlayIcon from "@/assets/play-icon";
import FireIcon from "@/assets/fire-icon";

import styles from "news-site-css/dist/article.module.css";

export default function ArticleTag({ tag }) {
    if (!tag)
        return null;

    return (
        <div className={classNames(
            styles["article-image-tag"],
            styles[tag.type]
        )}>
            { tag.type === "breaking" ? <LightningIcon /> : null }
            { tag.type === "watch" ? <PlayIcon /> : null }
            { tag.type === "new" ? <FireIcon /> : null }
            <ArticleText text={tag.label} />
        </div>
    );
}
