// resources/newssite/news-nuxt/components/atoms/Toggle.vue
<script lang="js">
import styles from "news-site-css/dist/toggle.module.css";

export default {
    props: {
        label: String,
        onChange: Function,
        checked: Boolean,
    },
    data() {
        return {
            styles,
            isSelected: false,
        }
    },
    mount() {
        this.isSelected = this.checked;
    },
    methods: {
        handleChange(e) {
            this.isSelected = e.target.checked;
            this.onChange(e);
        }
    }
}
</script>

<template>
    <div :class="styles['toggle-outer']">
        <div :class="styles['toggle-description']">
            {{ label }}
        </div>
        <div :class="styles['toggle-container']">
            <label :class="styles.label" for="reduced-motion-toggle">
                <input id="reduced-motion-toggle" type="checkbox" :checked="isSelected" @change="handleChange" />
                <span :class="styles.switch" />
                <div class="visually-hidden">selected: {{ isSelected ? "true" : "false" }}</div>
            </label>
        </div>
    </div>
</template>

// resources/newssite/news-next/src/components/toggle/toggle.jsx
import { useState, useEffect } from "react";

import styles from "news-site-css/dist/toggle.module.css";

export default function Toggle({ label, onChange, checked }) {
    const [isSelected, setIsSelected] = useState(false);

    useEffect(() => {
        setIsSelected(checked);
    }, [checked]);

    function handleChange(e) {
        setIsSelected(e.target.checked);
        onChange(e);
    }

    return (
        <div className={styles["toggle-outer"]}>
            <div className={styles["toggle-description"]}>{label}</div>
            <div className={styles["toggle-container"]}>
                <label className={styles.label} htmlFor="reduced-motion-toggle">
                    <input type="checkbox" id="reduced-motion-toggle" checked={isSelected} onChange={handleChange} />
                    <span className={styles.switch}></span>
                    <div className="visually-hidden">selected: {isSelected ? "true" : "false"}</div>
                </label>
            </div>
        </div>
    );
}
