// resources/newssite/news-nuxt/components/atoms/NavlistItem.vue
<script lang="js">
import styles from "news-site-css/dist/navbar.module.css";
export default {
  props: {
    label: String,
    url: String,
    callback: Function,
    id: String,
  },
  data () {
    return {
      styles,
    }
  }
}
</script>

<template>
  <NuxtLink
    :id="id"
    :active-class="styles['active']"
    :to="url"
    @click="callback"
  >
    {{ label }}
  </NuxtLink>
</template>

// resources/tentative/newssite/news-next/src/components/navlist/navlist-item.jsx
import { NavLink } from "react-router-dom";
import classNames from "classnames";

import styles from "news-site-css/dist/navbar.module.css";

export default function NavListItem({ id, label, url, callback, itemClass }) {
    return (
        <li className={classNames(
            styles["navbar-item"],
            itemClass
        )} onClick={callback}>
            <NavLink to={url} id={id} className={({ isActive }) => classNames({ [styles.active]: isActive })}>
                {label}
            </NavLink>
        </li>
    );
}
