// resources/newssite/news-next/src/partials/layout/Layout.jsx
import { useEffect, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import { HashLink } from "react-router-hash-link";

import Header from "../header/header";
import Navigation from "../navigation/navigation";
import Main from "../main/main";
import Footer from "../footer/footer";

import { content } from "@/data/content";
import { Message } from "@/components/message/message";

import styles from "news-site-css/dist/layout.module.css";

export default function Layout({ children, id }) {
    const [showMessage, setShowMessage] = useState(false);

    useEffect(() => {
        setShowMessage(content[id].message);
    }, [id]);

    const pageRef = useRef(null);
    const { pathname } = useLocation();

    useEffect(() => {
        pageRef?.current?.scrollTo({ top: 0, left: 0, behavior: "instant" });
    }, [pathname]);

    function closeMessage() {
        setShowMessage(false);
    }

    return (
        <>
            <HashLink to={`${pathname}#content`} className="skip-link">Skip to content</HashLink>
            <div className={styles.page} ref={pageRef}>
                <Header />
                <Navigation />
                { showMessage ? <Message message={content[id].message} onClose={closeMessage}/> : null }
                <Main>
                    {children}
                </Main>
                <Footer />
            </div>
        </>
    );
}

// resources/newssite/news-nuxt/components/organisms/Layout.vue
<script setup>
import { ref, inject, onMounted } from "vue";
import { useRoute } from "nuxt/app";
import styles from "news-site-css/dist/layout.module.css";

const showMessage = ref(false);
const route = useRoute();

const { content, links } = inject("data");

onMounted(() => {
    showMessage.value = content[route.name].message;
});

const closeMessage = () => {
    showMessage.value = false;
};
</script>

<template>
    <NuxtLink :to="`${route.path}#content`" class="skip-link">
        {{ links.a11y.skip.label }}
    </NuxtLink>
    <div id="page" :class="styles.page">
        <Header />
        <Navigation />
        <Message v-if="content[route.name].message" v-show="showMessage" :on-close="closeMessage" :message="content[route.name].message" />
        <Main>
            <slot />
        </Main>
        <Footer />
    </div>
</template>
