// resources/todomvc/architecture-examples/react/src/todo/components/Footer.jsx
import { useCallback } from "react";

export function Footer({ todos, onClear }) {
    const activeTodos = todos.filter((todo) => !todo.completed);

    const handleOnClear = useCallback(() => {
        onClear();
    }, [onClear]);

    if (todos.length === 0) {
        return null;
    }

    return (
        <footer className="footer" data-testid="footer">
            <span className="todo-count">{`${activeTodos.length} ${activeTodos.length === 1 ? "item" : "items"} left!`}</span>
            <ul className="filters" data-testid="footer-navigation">
                <li>
                    <a href="#/">All</a>
                </li>
                <li>
                    <a href="#/active">Active</a>
                </li>
                <li>
                    <a href="#/completed">Completed</a>
                </li>
            </ul>
            <button className="clear-completed" disabled={activeTodos.length === todos.length} onClick={handleOnClear}>
                Clear completed
            </button>
        </footer>
    );
}

// resources/todomvc/architecture-examples/svelte/src/Footer.svelte
<script>
    import { createEventDispatcher } from 'svelte';

    const dispatch = createEventDispatcher();

    function removeCompletedItems(e) {
        dispatch('removeCompletedItems');
    }

    export let numActive;
    export let currentFilter;
    export let numCompleted;
</script>

<footer class="footer">
    <span class="todo-count">
        <strong>{numActive}</strong>
        {numActive === 1 ? "item" : "items"} left
    </span>

    <ul class="filters">
        <li><a class={currentFilter === "all" ? "selected" : ""} href="#/">All</a></li>
        <li><a class={currentFilter === "active" ? "selected" : ""} href="#/active">Active</a></li>
        <li><a class={currentFilter === "completed" ? "selected" : ""} href="#/completed">Completed</a></li>
    </ul>

    {#if numCompleted}
        <button class="clear-completed" on:click={removeCompletedItems}> Clear completed </button>
    {/if}
</footer>
