// resources/todomvc/architecture-examples/react/src/todo/components/Item.jsx
import { memo, useState, useCallback } from "react";

import { Input } from "./input";

export const Item = memo(function Item({ todo, dispatch }) {
    const [isWritable, setIsWritable] = useState(false);
    const { title, completed, id } = todo;

    const toggleItem = useCallback(() => dispatch({ type: "TOGGLE_ITEM", payload: { id } }), [dispatch]);
    const removeItem = useCallback(() => dispatch({ type: "REMOVE_ITEM", payload: { id } }), [dispatch]);
    const updateItem = useCallback((id, title) => dispatch({ type: "UPDATE_ITEM", payload: { id, title } }), [dispatch]);

    const handleDoubleClick = useCallback(() => {
        setIsWritable(true);
    });

    const handleBlur = useCallback(() => {
        setIsWritable(false);
    });

    const handleUpdate = useCallback(
        (title) => {
            if (title.length === 0) {
                removeItem(id);
            } else {
                updateItem(id, title);
            }

            setIsWritable(false);
        },
        [id, removeItem, updateItem]
    );

    return (
        <li data-testid="todo-item">
            <div className="view">
                {isWritable ? (
                    <Input onSubmit={handleUpdate} label="Edit Todo Input" defaultValue={title} onBlur={handleBlur} />
                ) : (
                    <>
                        <input className="toggle" type="checkbox" data-testid="todo-item-toggle" checked={completed} onChange={toggleItem} />
                        <label data-testid="todo-item-label" onDoubleClick={handleDoubleClick}>
                            {title}
                        </label>
                        <button className="destroy" data-testid="todo-item-button" onClick={removeItem} />
                    </>
                )}
            </div>
        </li>
    );
});

// resources/todomvc/architecture-examples/svelte/src/Item.svelte
<script>
    import { createEventDispatcher, tick } from 'svelte';

    let editing = false;

    const dispatch = createEventDispatcher();

    function removeItem() {
        dispatch('removeItem');
    }

    function startEdit() {
       editing = true;
    }

    function handleEdit(event) {
        if (event.key === "Enter")
            event.target.blur();
        else if (event.key === "Escape") 
            editing = false;
    }

    function updateItem(event) {
        if (!editing) return;
        const { value } = event.target;
        if (value.length) {
            item.description = value;
        } else {
          removeItem();
        }
        editing = false;
    }

    function toggleItem(event) {
        dispatch('toggleItem', { checked: event.target.checked });
    }

    async function focusInput(element) {
		await tick();
		element.focus();
	}

    export let item;
</script>

<li class="{item.completed ? 'completed' : ''} {editing ? 'editing' : ''}">
    <div class="view">
        <input class="toggle" type="checkbox" on:change={toggleItem} checked={item.completed} />
        <!-- svelte-ignore a11y-label-has-associated-control -->
        <label on:dblclick={startEdit}>{item.description}</label>
        <button on:click={removeItem} class="destroy" />
    </div>

    {#if editing}
        <div class="input-container">
            <input value={item.description} id="edit-todo-input" class="edit" on:keydown={handleEdit} on:blur={updateItem} use:focusInput />
            <label class="visually-hidden" for="edit-todo-input">Edit Todo Input</label>
        </div>
    {/if}
</li>
