// resources/todomvc/architecture-examples/vue/src/components/TodoFooter.vue
<template>
     <footer class="footer" v-show="todos.length > 0">
        <span class="todo-count">
            <strong>{{ remaining }}</strong> {{ pluralizedWord }} left
        </span>
        <ul class="filters">
            <li><router-link to="/" :class="{ selected: route == 'all' }">All</router-link></li>
            <li><router-link to="/active" :class="{ selected: route == 'active' }">Active</router-link></li>
            <li><router-link to="/completed" :class="{ selected: route == 'completed' }">Completed</router-link></li>
        </ul>
        <button class="clear-completed" v-show="completed" @click="$emit('delete-completed')">Clear Completed</button>
    </footer>
</template>

<script>
export default {
    name: 'TodoFooter',
    props: {
        todos: Array,
        remaining: Number,
        route: String,
        completed: Number
    },
    computed: {
        pluralizedWord() {
            return this.remaining === 1 ? 'item' : 'items'
        },
    },
    emits: ['delete-completed']
}
</script>

// resources/todomvc/architecture-examples/angular/src/app/todo-footer/todo-footer.component.ts
import { Component } from "@angular/core";
import { Location } from "@angular/common";
import { Todo } from "../todo";
import { TodosService } from "../todos.service";

@Component({
    selector: "app-todo-footer",
    templateUrl: "./todo-footer.component.html",
})
export class TodoFooterComponent {
    constructor(
        private todosService: TodosService,
        private location: Location
    ) {}

    get todos(): Todo[] {
        return this.todosService.getItems();
    }

    get activeTodos(): Todo[] {
        return this.todosService.getItems("active");
    }

    get completedTodos(): Todo[] {
        return this.todosService.getItems("completed");
    }

    get filter(): string {
        return this.location.path().split("/")[1] || "all";
    }

    clearCompleted() {
        this.todosService.clearCompleted();
    }
}

<footer class="footer" *ngIf="todos.length > 0">
    <span class="todo-count"><strong>{{activeTodos.length}}</strong> {{activeTodos.length == 1 ? 'item' : 'items'}} left</span>
    <ul class="filters">
        <li>
            <a routerLink="/" [class.selected]="filter === 'all'">
                All
            </a>
        </li>
        <li>
            <a routerLink="/active" [class.selected]="filter === 'active'">
                Active
            </a>
        </li>
        <li>
            <a routerLink="/completed" [class.selected]="filter === 'completed'">
                Completed
            </a>
        </li>
    </ul>
    <button *ngIf="completedTodos.length" type="button" class="clear-completed" (click)="clearCompleted()">Clear Completed</button>
</footer>
