// resources/todomvc/architecture-examples/vue/src/components/TodoItem.vue
<template>
    <li
        :class="{
            targeted: true,
            [`li-${this.index}`]: true,
            completed: this.todo.completed,
            editing: this.editing,
        }"
        :data-priority="4 - (this.index % 5)"
    >
        <div :class="{ targeted: true, [`view-${this.index}`]: true }">
            <input type="checkbox" class="toggle" v-model="toggleModel" />
            <label @dblclick="startEdit">{{ todo.title }}</label>
            <button class="destroy" @click.prevent="deleteTodo"></button>
        </div>
        <div class="input-container">
            <input
                id="edit-todo-input"
                ref="editInputRef"
                type="text"
                class="edit"
                v-model="editModel"
                @keyup.enter="finishEdit"
                @blur="cancelEdit"
            />
            <label class="visually-hidden" for="edit-todo-input">Edit Todo Input</label>
        </div>
    </li>
</template>

<script>
import { nextTick } from "vue";
export default {
    name: "TodoItem",
    props: {
        todo: {
            title: String,
            completed: Boolean,
            id: Number,
        },
        index: Number,
    },
    data() {
        return {
            editText: "",
            editing: false,
        };
    },
    methods: {
        startEdit() {
            this.editing = true;
            nextTick(() => {
                this.focusEditInput();
            });
        },
        finishEdit() {
            this.editing = false;
            // prettier-ignore
            if (this.editText.trim().length === 0)
                this.deleteTodo();
            else
                this.updateTodo();
        },
        cancelEdit() {
            this.editing = false;
        },
        focusEditInput() {
            this.$refs.editInputRef.focus();
        },
        deleteTodo() {
            this.$emit("delete-todo", this.todo);
        },
        updateTodo() {
            this.$emit("edit-todo", this.todo, this.editText);
            this.editText = "";
        },
    },
    computed: {
        toggleModel: {
            get() {
                return this.todo.completed;
            },
            set(value) {
                this.$emit("toggle-todo", this.todo, value);
            },
        },
        editModel: {
            get() {
                return this.todo.title;
            },
            set(value) {
                this.editText = value;
            },
        },
    },
    emits: ["edit-todo", "delete-todo", "toggle-todo"],
};
</script>

// resources/todomvc/architecture-examples/angular/src/app/todo-item/todo-item.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, AfterViewChecked, ChangeDetectionStrategy } from '@angular/core';
import { Todo } from '../todo';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoItemComponent implements AfterViewChecked{
  @Input() todo:Todo = new Todo("", "", false);

  @Output() toggleEvent = new EventEmitter<Todo>();
  @Output() deleteEvent = new EventEmitter<Todo>();
  @Output() updateEvent = new EventEmitter<{todo: Todo, title: string}>();

  @ViewChild('todoInputRef') inputRef: ElementRef | undefined; 

  isEditing:boolean = false;

  toggleTodo(todo:Todo):void {
    this.toggleEvent.emit(todo);
  }

  removeTodo(todo:Todo):void {
    this.deleteEvent.emit(todo);
  }

  startEdit() {
    this.isEditing = true;
  }

  handleBlur(e:Event) {
    this.isEditing = false;
  }

  updateTodo(todo: Todo, title: string) {
    const todoTitle = title.trim();
    if (todoTitle.length <= 0)
      this.deleteEvent.emit(todo);
    else 
      this.updateEvent.emit({todo, title});

    this.isEditing = false;
  }

  ngAfterViewChecked(): void {
    if (this.isEditing) {
      if (this.inputRef) this.inputRef.nativeElement.focus();
    }
  }
}

<li [ngClass]="{ completed: todo.completed, editing: isEditing }" [attr.data-priority]="4 - (index % 5)">
    <div class="view">
        <input class="toggle" type="checkbox" (click)="toggleTodo()" [checked]="todo.completed" />
        <label (dblclick)="startEdit()">{{ todo.title }}</label>
        <button class="destroy" (click)="removeTodo()"></button>
    </div>
    <div *ngIf="isEditing" class="input-container">
        <input
            #todoInputRef
            class="edit"
            id="edit-todo-input"
            (focus)="handleFocus($event)"
            (blur)="handleBlur($event)"
            (keyup.enter)="updateTodo()"
            [formControl]="titleFormControl"
        />
        <label class="visually-hidden" htmlFor="edit-todo-input"> Edit Todo Input </label>
    </div>
</li>
