// resources/newssite/news-next/src/components/article/article-image.jsx
import Image from "next/image";
import ArticleText from "./article-text";
import ArticleTag from "./article-tag";

import styles from "news-site-css/dist/article.module.css";

export default function ArticleImage({ image, imageClass, meta }) {
    if (!image)
        return null;

    return (
        <>
            <div className={imageClass} style={{ width: "auto" }}>
                <Image className={styles["article-image"]} src={`./${image.src}`} width={image.width} height={image.height} alt={image.alt} />
                <ArticleTag tag={meta?.tag} />
            </div>
            <ArticleText textClass={styles["article-image-captions"]} text={meta?.captions} />
        </>
    );
}

// resources/newssite/news-nuxt/components/atoms/ArticleImage.vue
<script lang="js">
import styles from "news-site-css/dist/article.module.css";

export default {
    props: {
        image: Object,
        imageClass: String,
        meta: Object,
    },
    data() {
        return {
            styles
        }
    }
}
</script>

<template>
    <div v-if="image" :class="imageClass" style="width: auto;">
        <img :class="styles['article-image']" :src="image.src" :width="image.width" :height="image.height" :alt="image.alt" />
        <ArticleTag :tag="meta?.tag" />
    </div>
    <ArticleText :text-class="styles['article-image-captions']" :text="meta?.captions" />
</template>
