// resources/newssite/news-next/src/components/message/message.jsx
import classNames from "classnames";

import styles from "news-site-css/dist/message.module.css";

export function Message({ message, onClose }) {
    if (!message)
        return null;

    const { title, description } = message;
    return (
        <div className={classNames(styles.message, styles.open)}>
            <button
                id="close-message-link"
                className={styles["message-close-button"]}
                onClick={onClose}
                title="Close Button"
            >
                <div
                    className={classNames(styles["message-close-button-icon"], "animated-icon", "close-icon", "hover")}
                    title="Close Icon"
                >
                    <span className="animated-icon-inner">
                        <span></span>
                        <span></span>
                    </span>
                </div>
            </button>
            {title
                ? <header className={styles["message-header"]}>
                    <h2>{title}</h2>
                </header>
                : null}
            <section className={styles["message-body"]}>
                <div className={styles["message-description"]}>{description}</div>
            </section>
        </div>
    );
}

// resources/newssite/news-nuxt/components/atoms/Message.vue
<script lang="js">
import styles from "news-site-css/dist/message.module.css";

export default {
    props: {
        onClose: Function,
        message: Object,
    },
    data() {
        return {
            styles,
        };
    },
};
</script>

<template>
    <div :class="[styles.message, styles.open]">
        <button id="close-message-link" :class="styles['message-close-button']" title="Close Button" @click="onClose">
            <div :class="[styles['message-close-button-icon'], 'animated-icon', 'close-icon', 'hover']" title="Close Icon">
                <span class="animated-icon-inner">
                    <span />
                    <span />
                </span>
            </div>
        </button>
        <header v-if="message.title" :class="styles['message-header']">
            <h2>{{ message.title }}</h2>
        </header>
        <section :class="styles['message-body']">
            <div :class="styles['message-description']">
                {{ message.description }}
            </div>
        </section>
    </div>
</template>
