// resources/todomvc/architecture-examples/angular/src/app/todo-header/todo-header.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { TodosService } from '../todos.service';

@Component({
  selector: 'app-todo-header',
  templateUrl: './todo-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoHeaderComponent {
  constructor(private todosService: TodosService) {}

  addTodo(title: string) {
    const todoTitle = title.trim();
    if (todoTitle.length <= 0)
      return;

    this.todosService.addItem(todoTitle);
  }
}

<header class="header">
    <h1>todos</h1>
    <input #headerInputRef class="new-todo" placeholder="What needs to be done?" autofocus="" (keyup.enter)="addTodo(headerInputRef.value); headerInputRef.value = ''">
</header>

// resources/todomvc/architecture-examples/vue/src/components/TodoHeader.vue
<template>
    <header class="header">
        <h1>Todos</h1>
        <input
            type="text"
            class="new-todo"
            autofocus
            autocomplete="off"
            placeholder="What needs to be done?"
            @keyup.enter="
                $emit('add-todo', $event.target.value);
                $event.target.value = '';
            "
        />
    </header>
</template>

<script>
export default {
    name: "TodoHeader",
    emits: ["add-todo"],
};
</script>
